# -*- coding: utf-8 -*-
from __future__ import division
import sys
from PyQt4 import QtCore, QtGui, uic
# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

# from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(794, 496)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.price_box = QtGui.QTextEdit(self.centralWidget)
        self.price_box.setGeometry(QtCore.QRect(40, 60, 121, 31))
        self.price_box.setObjectName(_fromUtf8("price_box"))
        self.results_window = QtGui.QTextEdit(self.centralWidget)
        self.results_window.setGeometry(QtCore.QRect(40, 150, 261, 31))
        self.results_window.setObjectName(_fromUtf8("results_window"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.tax_rate = QtGui.QSpinBox(self.centralWidget)
        self.tax_rate.setGeometry(QtCore.QRect(230, 60, 101, 31))
        self.tax_rate.setProperty("value", 20)
        self.tax_rate.setObjectName(_fromUtf8("tax_rate"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.calc_tax_button = QtGui.QPushButton(self.centralWidget)
        self.calc_tax_button.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.calc_tax_button.setObjectName(_fromUtf8("calc_tax_button"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuCapture = QtGui.QMenu(self.menuBar)
        self.menuCapture.setObjectName(_fromUtf8("menuCapture"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionRecent_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Files.setObjectName(_fromUtf8("actionRecent_Files"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionExamples = QtGui.QAction(MainWindow)
        self.actionExamples.setObjectName(_fromUtf8("actionExamples"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionFind_Next = QtGui.QAction(MainWindow)
        self.actionFind_Next.setObjectName(_fromUtf8("actionFind_Next"))
        self.actionGoto = QtGui.QAction(MainWindow)
        self.actionGoto.setObjectName(_fromUtf8("actionGoto"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionEvent_Trigger = QtGui.QAction(MainWindow)
        self.actionEvent_Trigger.setObjectName(_fromUtf8("actionEvent_Trigger"))
        self.actionBuffer_Setting = QtGui.QAction(MainWindow)
        self.actionBuffer_Setting.setObjectName(_fromUtf8("actionBuffer_Setting"))
        self.actionMessage_View = QtGui.QAction(MainWindow)
        self.actionMessage_View.setObjectName(_fromUtf8("actionMessage_View"))
        self.actionRaw_Data = QtGui.QAction(MainWindow)
        self.actionRaw_Data.setObjectName(_fromUtf8("actionRaw_Data"))
        self.actionAbout_PD_Analyzer = QtGui.QAction(MainWindow)
        self.actionAbout_PD_Analyzer.setObjectName(_fromUtf8("actionAbout_PD_Analyzer"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent_Files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExamples)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFind_Next)
        self.menuEdit.addAction(self.actionGoto)
        self.menuCapture.addAction(self.actionConnect)
        self.menuCapture.addAction(self.actionDisconnect)
        self.menuCapture.addAction(self.actionRun)
        self.menuCapture.addAction(self.actionPause)
        self.menuCapture.addAction(self.actionStop)
        self.menuCapture.addAction(self.actionEvent_Trigger)
        self.menuCapture.addAction(self.actionBuffer_Setting)
        self.menuView.addAction(self.actionMessage_View)
        self.menuView.addAction(self.actionRaw_Data)
        self.menuAbout.addAction(self.actionAbout_PD_Analyzer)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuCapture.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "USB PD Analyzer", None))
        self.label.setText(_translate("MainWindow", "Price", None))
        self.label_2.setText(_translate("MainWindow", "Result", None))
        self.calc_tax_button.setText(_translate("MainWindow", "Calculate", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionRecent_Files.setText(_translate("MainWindow", "Recent Files", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionExport.setText(_translate("MainWindow", "Export", None))
        self.actionExamples.setText(_translate("MainWindow", "Examples", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionFind.setText(_translate("MainWindow", "Find", None))
        self.actionFind_Next.setText(_translate("MainWindow", "Find Next", None))
        self.actionGoto.setText(_translate("MainWindow", "Goto", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.actionRun.setText(_translate("MainWindow", "Run", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionEvent_Trigger.setText(_translate("MainWindow", "Event Trigger", None))
        self.actionBuffer_Setting.setText(_translate("MainWindow", "Buffer Setting", None))
        self.actionMessage_View.setText(_translate("MainWindow", "Message View", None))
        self.actionRaw_Data.setText(_translate("MainWindow", "Raw Data", None))
        self.actionAbout_PD_Analyzer.setText(_translate("MainWindow", "About PD Analyzer", None))

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    window = Ui_MainWindow()
    window.show()
    sys.exit(app.exec_())